#!/usr/bin/ruby
require 'rubygems'
require '~/.irb/gem_loader'
require '~/.irb/pry_loader'
require '~/.irb/custom' if File.exists?("#{Dir.home}/.irb/irb/custom.rb")

if defined? ::Pry
  IRB::TopLevel.new.pry
  exit
end
