if not set -q git_abbrs_initialized
  set -U git_abbrs_initialized
  abbr gb 'git branch'
  abbr gbc 'git checkout -b'
  abbr gbl 'git branch -v'
  abbr gbx 'git branch -d'
  abbr gbX 'git branch -D'
  abbr gc 'git commit --verbose'
  abbr gcm 'git commit --message'
  abbr gco 'git checkout'
  abbr gf 'git fetch'
  abbr gfc 'git clone'
  abbr gfr 'git pull --rebase'
  abbr gia 'git add'
  abbr giA 'git add --patch'
  abbr gid 'git diff --no-ext-diff --cached'
  abbr gir 'git reset'
  abbr gix 'git rm -r --cached'
  abbr gl 'git log --format="%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit'
  abbr gls 'git log --stat'
  abbr glp 'git log -p'
  abbr gm 'git merge'
  abbr gmF 'git merge --no-ff'
  abbr gma 'git merge --abort'
  abbr gmt 'git mergetool'
  abbr gp 'git push'
  abbr gpc 'git push --set-upstream origin (branch_current 2> /dev/null)'
  abbr gr 'git rebase'
  abbr gs 'git stash'
  abbr gsp 'git stash pop'
  abbr gws 'git status --short'
  abbr gwd 'git diff --no-ext-diff'
  abbr gwx 'git rm -r'
  abbr gwX 'git rm -rf'
end
